### ISSUE TITLE
ExecException incorrectly extends interface error.

### ISSUE THREAD

**Issue by vamsidogiparthi** [diachedelic/capacitor-blob-writer#14]
I tried using the blob storage plugin in my project. But when my build runs its throwing me the below error. I tried look at the issue why this plugin is providing issue with a type inside @types/nodes module of my project and found that you have been using error interface with code? as string which contradicts with what @types/nodes global config is. 

I want to know what's the work around as my project dependencies are installed by npm on run time, same as well with capacitor blob storage plugin. I don't have control on both of the libraries.

![image](https://user-images.githubusercontent.com/30355728/86635486-220ae280-bfa1-11ea-8c86-b287140d3539.png)
![image](https://user-images.githubusercontent.com/30355728/86635767-862da680-bfa1-11ea-95d5-1fb92f75e020.png)
![image](https://user-images.githubusercontent.com/30355728/86635801-9180d200-bfa1-11ea-8082-8a7d6e232478.png)

**Comment by diachedelic** [comment]
Fixed in v0.1.8, thanks

**Comment by vamsidogiparthi** [comment]
Thanks will test it again my getting newer version from npm.
