### ISSUE TITLE
Error when building Android

### ISSUE THREAD

**Issue by thanhhoa214** [diachedelic/capacitor-blob-writer#17]
# Error when building Android:

First thing I need to say thanks for the great idea, to build in-app-server and write files. You did a good job on iOS but seemly Android does not work well. Please help. 

- I did the same as instructions step-by-step, built with `ionic capacitor run android` and finally click `▶️` in **Android. Studio**.
- Expected: Running on my device
- Result: 
```
/....../node_modules/capacitor-blob-writer/android/src/main/java/com/equimaps/capacitorblobwriter/BlobWriter.java:58: error: no suitable method found for error(String,String,<null>)
            call.error("Server not running", "SERVER_DOWN", null);
                ^
    method PluginCall.error(String, Exception) is not applicable
      (actual and formal argument lists differ in length)
    method PluginCall.error(String) is not applicable

```
### **Build Output Detail Tab**
![Screen Shot 2020-07-29 at 15 48 22](https://user-images.githubusercontent.com/32329202/88778631-f1d6ee00-d1b2-11ea-8ba6-73c8acfaf636.png)

### **Build Output**
![Screen Shot 2020-07-29 at 15 48 47](https://user-images.githubusercontent.com/32329202/88778674-00bda080-d1b3-11ea-85be-b22d2b683399.png)

### **Error at line `58` of `BlobWriter.java`: `server` null but I don't know why**
![Screen Shot 2020-07-29 at 15 50 55](https://user-images.githubusercontent.com/32329202/88778897-4bd7b380-d1b3-11ea-9771-9437e67707f9.png)

**Comment by diachedelic** [comment]
It appears you are using Capacitor v1.x, which it turns out is not supported :( - I have added a warning to the readme. Can you please upgrade to Capacitor v2 and see if that solves your issue?

Thanks for the detailed reporting!

**Comment by diachedelic** [comment]
Actually, I've made that call backwards compatible in `0.1.9` - can you please see if it works with your version of capacitor?

**Comment by thanhhoa214** [comment]
I turned my app to Capacitor v2 so it works as expected. Sorry I missed reading your README. Big hug, guy.
