### ISSUE TITLE
Bug Report: Run on Android but receiving "Not implement for web"

### ISSUE THREAD

**Issue by thanhhoa214** [diachedelic/capacitor-blob-writer#18]
### **Download encrypted file** >>>> **Read, decrypt and re-write a temp file**

![Screen Shot 2020-07-31 at 11 56 24](https://user-images.githubusercontent.com/32329202/89001597-dd1a6780-d324-11ea-9c54-338677aa21ad.png)

✅ Reading passed
✅ Decrypting passed
❌ Re-writing error
 
### Here's my code:
Don't mind about `path`, I checked it.
![Screen Shot 2020-07-31 at 12 10 50](https://user-images.githubusercontent.com/32329202/89002291-e3a9de80-d326-11ea-9979-cf6e064d4f8e.png)

### Many thanks and please help!

**Comment by diachedelic** [comment]
Strange! Have you properly configured BlobWriter in your MainActivity.java? Can you post the output of `await Plugins.Device.getInfo()` from your Android?

**Comment by thanhhoa214** [comment]
It's really strange.
<img width="282" alt="Screen Shot 2020-08-01 at 07 44 32" src="https://user-images.githubusercontent.com/32329202/89090159-45238900-d3cb-11ea-8252-2b9ecaa19727.png">

**Comment by diachedelic** [comment]
In your device logs (in Android Studio) do you see any reference to BlobWriter? It should log if the plugin loads successfully.

**Comment by thanhhoa214** [comment]
I don't know why actually. Now it worked without any fix. I closed this issue. 

## 👍👍👍 Thanks for your help.
