### ISSUE TITLE
'registerWebPlugin' is deprecated

### ISSUE THREAD

**Issue by leo6104** [diachedelic/capacitor-blob-writer#23]
![image](https://user-images.githubusercontent.com/7777929/106098007-a3170a80-617b-11eb-8e57-b49147849e8f.png)

I saw that this plugin have console.warn about deprecated functions.

**Comment by diachedelic** [comment]
Thanks for pointing this out. Does it work with Capacitor v3 for you?

**Comment by leo6104** [comment]
Yes. it works with Capacitor 3 ! 
Thanks for awesome plugin. :)

**Comment by diachedelic** [comment]
Good to know! I will aim to fix this sometime before Capacitor v4 is released.

**Comment by jfbloom22** [comment]
@leo6104 did you do anything special to get this working in Capacitor 3?   I am running into these build errors:

```
node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    Property 'BlobWriter' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'.

16 export interface CapacitorInstance extends CapacitorGlobal {
                    ~~~~~~~~~~~~~~~~~

  node_modules/capacitor-blob-writer/dist/index.d.ts:4:9
    4         BlobWriter: BlobWriterPlugin;
              ~~~~~~~~~~
    'BlobWriter' is declared here.
node_modules/capacitor-blob-writer/dist/index.d.ts:1:10 - error TS2305: Module '"@capacitor/core"' has no exported member 'FilesystemDirectory'.

1 import { FilesystemDirectory } from '@capacitor/core';
```

**Comment by diachedelic** [comment]
Based on my experience upgrading another plugin of mine (which was quite involved), I would be very surprised if this plugin is compatible with Capacitor v3 in its current form. It needs upgrading.

**Comment by leo6104** [comment]
@diachedelic As i know, `interface PluginRegistry` logic should be removed on capacitor v3. 

https://github.com/diachedelic/capacitor-blob-writer/blob/master/src/index.ts#L9

**Comment by jfbloom22** [comment]
@leo6104 I just submitted my PR for the same.  Haha I wish I had noticed your PR two days ago it would have given me more of a head start. It looks like I made it a little further since I updated the pods and have tested it in my Capacitor 3 app.  Please check it out and let me know if there is anything I can improve on it.  https://github.com/diachedelic/capacitor-blob-writer/pull/30

**Comment by diachedelic** [comment]
Please try version 1 of the plugin, it should support Capacitor v3. Thanks for your pull requests, they helped a lot.
