### ISSUE TITLE
Question: Is the server externally accessible too?

### ISSUE THREAD

**Issue by beruic** [diachedelic/capacitor-blob-writer#27]
The possibility to push files to the device from another, by letting them share credentials and port numbers would open up for some interesting use cases for multi device file sharing on a local network.

**Comment by diachedelic** [comment]
The server is not accessible to the local network, see #12.

Allowing one app to write to another's filesystem directly would tightly couple them. If an app needs to receive information from another app, it should expose a well defined interface, which is not the purpose of this plugin.
