### ISSUE TITLE
Capacitor 3 support

### ISSUE THREAD

**Issue by AE1NS** [diachedelic/capacitor-blob-writer#31]
Will you update the plugin to support Capacitor 3?

**Comment by diachedelic** [comment]
Please see if version 1 of the plugin works for you.

**Comment by AE1NS** [comment]
Thanks for updating the repository and sorry for the late response!

In Android it seems to work fine.

Unfortunately I get this error when running it in iOS:
```
Error: Plugin BlobWriter does not respond to method call "get_config" using selector "get_config:".
⚡️  Ensure plugin method exists, uses @objc in its declaration, and arguments match selector without callbacks in CAP_PLUGIN_METHOD.
⚡️  Learn more: https://capacitorjs.com/docs/plugins/ios/#defining-methods
```

**Comment by diachedelic** [comment]
Hey @AE1NS , can you please follow the steps listed in #32 and see if it is resolved?

**Comment by AE1NS** [comment]
`Product > Clean Build Folder` did the trick!

**Comment by diachedelic** [comment]
Thanks, I've added it to the documentation.
