### ISSUE TITLE
definitions.d.ts missing from 1.0.0

### ISSUE THREAD

**Issue by codeluggage** [diachedelic/capacitor-blob-writer#33]
Hi there :wave:

Thanks for this great plugin! 

I have been working with Capacitor 3 lately, and when installing `1.0.0`, I don't see any `definitions.d.ts` in `node_modules/capacitor-blob-writer`. 

Here's my `ls` of the `node_modules/capacitor-blob-writer`:

```
CapacitorBlobWriter.podspec blob_writer.js              ios
LICENSE                     blob_writer.umd.js          package.json
README.md                   blob_writer.umd.js.map
android
```

When I add https://github.com/diachedelic/capacitor-blob-writer/blob/master/definitions.d.ts directly to the folder, it seems to do the trick.

**Comment by diachedelic** [comment]
Thanks, please try v1.0.1
