### ISSUE TITLE
Filesystem.readFile after write returns invalid base64?

### ISSUE THREAD

**Issue by mrobst** [diachedelic/capacitor-blob-writer#36]
Thanks for this plugin, its working great on saving larger videos for me. I did find one (potential) issue - if I write a normal size file (e.g. photo from the camera) with this plugin and then read it back using Filsystem.readFile I seem to get malformed base64 result. Is this a known issue? At the moment I need to have separate logic for photos from the camera (saved with Filesystem.writeFile) and larger video files from the filesystem and it would be better to consolidate this. 

I'm using capacitor v2 with v 0.2.4 of capacitor-blob-writer. My relevant imports look like this: 

import { Plugins, Capacitor, CameraPhoto } from '@capacitor/core'
import { Camera, Filesystem } = Plugins
import { writeFile } from 'capacitor-blob-writer'

I just came across this https://github.com/ionic-team/capacitor-plugins/issues/10 which seems to imply that Filesystem.<method> support for binary data is not yet available so I guess if I wanted to get base 64 I'd need to use fetch or similar with a ConvertFileSrc url (and then convert the result). 

thanks
Marcus

**Comment by diachedelic** [comment]
The tests [use `fetch` to read data from the filesystem](https://github.com/diachedelic/capacitor-blob-writer/blob/d2a1b1188c9465e765c1be87c607da6871350eea/demo/src/index.ts#L88), and I recommend you do too.
