### ISSUE TITLE
[BUG] Bump ios deployment target to 12.0

### ISSUE THREAD

**Issue by maxcodefaster** [diachedelic/capacitor-blob-writer#38]
When compiling, the build fails with latest capacitor see: https://capacitorjs.com/docs/updating/plugins/3-0#set-ios-deployment-target-to-120

**Comment by maxcodefaster** [comment]
Workaround: 
![image](https://user-images.githubusercontent.com/35369883/155510044-eb8c5bda-dca3-4c12-9b90-5fba375fee63.png)

**Comment by diachedelic** [comment]
This plugin [does](https://github.com/diachedelic/capacitor-blob-writer/blob/b4f655ea137738efcd87ae4bb070b6c3e280199e/ios/Plugin.xcodeproj/project.pbxproj#L378) target iOS 12.0.
