### ISSUE TITLE
Manipulate file with > 1GB

### ISSUE THREAD

**Issue by mannok** [diachedelic/capacitor-blob-writer#47]
I saw this plugin is capable to read and write file with over > 256MB in size. However, both mobile platforms crashed while the size reaches 512MB.

I am developing an app which needs to unzip a zip file with >1GB, is it possible?

**Comment by diachedelic** [comment]
Can you provide any error logs? It would be good to find out exactly what caused the crashes.

**Comment by mannok** [comment]
Sorry that I haven't tried yet. I am just asking because of the README Document stated that

- Android will crash as "Quota exceeded[2]" for 512MB
- iOS will crash as "WebKit error[2]" for 512MB

**Comment by diachedelic** [comment]
I'm sorry, I don't know what will happen with really large files. I would expect `write_blob` to go into fallback mode if the file is really big. The file will be written (if there is enough space on disk) but it will be written quite slowly.
