### ISSUE TITLE
Please make it compatible with Capacitor 4

### ISSUE THREAD

**Issue by damida80** [diachedelic/capacitor-blob-writer#48]
Hey, Capacitor 4 launched, it would be great if you could make the wonderful blob-writer compatible with that.

**Comment by diachedelic** [comment]
What happens if you use the plugin with Capacitor 4? Does it break?

**Comment by DanielMuster** [comment]
Thanks for your reply!
npm is not able to resolve the dependency to @capacitor/core@^3.0.0, so npm stops installing it, if Capacitor 4 is present (`npm install capacitor-blob-writer`). When I force the install, there are a lot of warnings, but the project actually compiles. Android Studio also compiles the project, starts it in the simulator without any errors, but the functionality is not given (the function write_blob() does not write anything anymore).

**Comment by diachedelic** [comment]
v1.1.1 should be compatible with Capacitor 4. Please test.

**Comment by damida80** [comment]
> v1.1.1 should be compatible with Capacitor 4. Please test.

Wow, thanks for implementing this that fast! The installation works now, I will check on the weekend if the plugin behaves as expected :)

**Comment by damida80** [comment]
> > v1.1.1 should be compatible with Capacitor 4. Please test.
> 
> Wow, thanks for implementing this that fast! The installation works now, I will check on the weekend if the plugin behaves as expected :)

Works like a charm, thank you again for that fast response!

**Comment by diachedelic** [comment]
I missed something in v1.1.1. As of Capacitor v4, there is additional configuration required: https://github.com/diachedelic/capacitor-blob-writer#ios.
