### ISSUE TITLE
Support Electron

### ISSUE THREAD

**Issue by diachedelic** [diachedelic/capacitor-blob-writer#5]
If there is enough interest I will consider supporting Electron, and will definitely review pull requests. Please discuss here.

**Comment by digaus** [comment]
Electron would be awesome.

**Comment by diachedelic** [comment]
Electron is now somewhat supported - `BlobWriter.writeFile` uses `Filesystem.writeFile` internally. However it does not have the performance of iOS/Android platforms.

**Comment by diachedelic** [comment]
How to write Electron plugin?
- https://github.com/ionic-team/capacitor/issues/1748#issuecomment-613401548

**Comment by diachedelic** [comment]
Closing due to lack of interest.
