### ISSUE TITLE
 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by NeluQi** [diachedelic/capacitor-blob-writer#50]
chrome
![image](https://user-images.githubusercontent.com/16963395/184637523-c49380e8-86fe-4458-963b-a0aa3b6bc79e.png)

![image](https://user-images.githubusercontent.com/16963395/184637444-4df61a53-ecee-4096-bad4-9ec159e7090e.png)
![image](https://user-images.githubusercontent.com/16963395/184637582-0bf519ac-bad5-4d8d-91e6-0c0dbf7e0db7.png)

**Comment by diachedelic** [comment]
This should be fixed in v1.1.3. Please test.
