### ISSUE TITLE
Feature: Bigger chunk size 

### ISSUE THREAD

**Issue by hraschan** [diachedelic/capacitor-blob-writer#52]
First of all its a greate plugin but I got the following question. Is their a possibility to increase the chunk size? 

I got a Zip of around 500MB and need to unzip and save every file to the file system. This process takes quite some time with the blob_writer. Is there a way to increase the speed?

**Comment by diachedelic** [comment]
The chunk size only affects fallback mode. You can either write the file to disk and unzip it with a native plugin, or unzip the file in JavaScript and write each file to disk. I suspect the first option will be faster, but probably not by much.

Are you sure you are not inadvertently running in fallback mode?
