### ISSUE TITLE
Raise iOS target to 13

### ISSUE THREAD

**Issue by AE1NS** [diachedelic/capacitor-blob-writer#56]
I saw this [capacitor 4 commit](https://github.com/diachedelic/capacitor-blob-writer/commit/32f117be4777fa49c34209daca4859140b24cb95). Unfortunately just the podfile inside the demo project was raised to target 13. Could you also raise https://github.com/diachedelic/capacitor-blob-writer/blob/master/ios/Podfile this to 13? Currently my XCode complains about it, because it does not have capacitors minimum target of 13.

**Comment by diachedelic** [comment]
Thanks, this is fixed in v1.1.5.

**Comment by AE1NS** [comment]
@diachedelic I still have build issues. Can you have a look at the CapacitorBlobWriter.podspec. There is a config 's.ios.deployment_target' and I think it must also be raised from 12 to 13. Thanks in advance!

**Comment by diachedelic** [comment]
Sure, fixed in v1.1.8.

**Comment by diachedelic** [comment]
Can you please check plugin v1.1.9 still works for you? I had to revert part of the change because it broke Capacitor v3 support.

**Comment by AE1NS** [comment]
In my case its working fine, but I only have a Capacitor 4 use case. Maybe you should change the version number of this plugin for the future, i.e.:
^3.0.0 = Capacitor 3 support
^4.0.0 = Capacitor 4 support
...

**Comment by diachedelic** [comment]
Thanks, that's all I wanted to know. I don't want to maintain two versions, so I'm hoping it works on both.

**Comment by AE1NS** [comment]
> Thanks, that's all I wanted to know. I don't want to maintain two versions, so I'm hoping it works on both.

Sorry, I edited my comment. I did not test 1.1.9, but the initial issue was target 12, so I think it will make trouble with cap4.

**Comment by diachedelic** [comment]
My testing shows that v1.1.9 works on both - both the `cap sync` and the Xcode build.

**Comment by AE1NS** [comment]
Thats possible depending on your setup, but in my opinion a capacitor plugin should always remain consistent with capacitor core, if it is marked as 'latest support'. Thats why many devs publish there plugin major version with the same number as capacitor core.

The capacitor 4 migration guide specifies to raise the ios deployment target:
https://capacitorjs.com/docs/updating/4-0#raise-ios-deployment-target
https://github.com/ionic-team/capacitor-plugins/pull/877
https://github.com/rdlabo-team/capacitor-plugin-to-v4
