### ISSUE TITLE
GDCWebServer not maintained, too old

### ISSUE THREAD

**Issue by Ralle** [diachedelic/capacitor-blob-writer#63]
Hey,
I'm a web dev with very scarce XCode experience. I tried installing your package but it fails to build now with this error in XCode:
```
      /Users/rasmus/Code/soundwheel/ios/App/Pods/Pods.xcodeproj: warning: The iOS deployment target
        'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to
        16.4.99. (in target 'GCDWebServer' from project 'Pods')
```

Is there something I can do?

**Comment by diachedelic** [comment]
This is what I do:

```
# Set the deployment target of all installed Pods to the same as this app.
# Avoids build errors, see https://stackoverflow.com/questions/75574268.
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end
```

Another solution would be to inline the GCDWebServer source code into this plugin, rather than depending on it as a Pod.

**Comment by diachedelic** [comment]
Just to clarify - that code goes in your app's Podfile.

**Comment by Ralle** [comment]
Oh thank you. I will try that. I did see this code snippet in other places, I just didn't know what to do with it :).

**Comment by eyecatchup** [comment]
Instead of updating all pods, you can set the deployment target version just for GCDWebServer in Xcode like so:

![Bildschirmfoto 2023-06-30 um 08 53 10](https://github.com/diachedelic/capacitor-blob-writer/assets/845131/6e48cbc6-76a2-4035-910b-bfda65b4f45a)
