### ISSUE TITLE
Getting error "Uncaught (in promise) Error: "BlobWriter.write_blob()" is not implemented on android"

### ISSUE THREAD

**Issue by Sempervivum** [diachedelic/capacitor-blob-writer#66]
I'm getting error "Uncaught (in promise) Error: "BlobWriter.write_blob()" is not implemented on android".
My code:
```
   <script src="bundle-blobwriter.js"></script>
    <script>
        try {
            exportsBlobwriter.Plugins.Filesystem.requestPermissions().then((status) => {
                console.log(status)
                exportsBlobwriter.CapacitorHttp.get({ url: 'https://example.com/path/example.db' })
                    .then(resp => {
                        setTimeout(() => {
                            exportsBlobwriter.Plugins.BlobWriter.write_blob({
                                path: 'file:///data/user/0/com.substanzen.app/databases/SubstancesSQLite.db',
                                data: resp.data,
                                fast_mode: true
                                // exports.Plugins.Filesystem.writeFile({
                                //     path: 'file:///data/user/0/com.substanzen.app/databases/SubstancesSQLite.db',
                                //     data: resp.data,
                                //     encoding: 'ascii',
                            }).then((result) => {
                                console.log(result)
                            });
                        }, 2000);
                    });
            });
        } catch (err) {
            console.log(`Error: ${err} `);
            throw new Error(`Error: ${err}`)
        }
    </script>
```
I bundled BlobWriter by use of browserify.js.
Capacitor V5 was installed several days ago.
Bundled javascript is attached.
![blobwriter-issue](https://github.com/diachedelic/capacitor-blob-writer/assets/6693087/89fa8c93-6b2c-4200-b855-410e6f8712aa)
[bundle-blobwriter.txt](https://github.com/diachedelic/capacitor-blob-writer/files/11925733/bundle-blobwriter.txt)

**Comment by diachedelic** [comment]
The published NPM package comes with a bundle you can use, `dist/plugin.umd.js`. Use that instead.

```html
<script src="path/to/node_modules/@capacitor/core/dist/capacitor.js"></script>
<script src="path/to/node_modules/capacitor-blob-writer/dist/plugin.umd.js"></script>
```

**Comment by Sempervivum** [comment]
First of all: I struggled for days as the import statements didn't work for me. Following your hint it's very easy to include Capacitor. Many thanks!

Unfortunately I didn't find a dist folder in node_modules/capacitor-blob-writer. I used blob_writer.umd.js from node_modules/capacitor-blob-writer but no success: I keep getting
"Uncaught (in promise) Error: "BlobWriter.write_blob()" is not implemented on android"
 My javascript:
```
    <script src="capacitor.js"></script>
    <script src="blob_writer.umd.js"></script>
    <script>
        try {
            Capacitor.Plugins.Filesystem.requestPermissions().then((status) => {
                console.log(status)
                Capacitor.Plugins.CapacitorHttp
                    .get({ url: 'https://webentwicklung.ulrichbangert.de/_benni/substanzen-electron/Substances.db' })
                    .then(resp => {
                        Capacitor.Plugins.BlobWriter.write_blob({
                            path: 'file:///data/user/0/com.substanzen.app/databases/SubstancesSQLite.db',
                            data: resp.data,
                            fast_mode: true
                            // exports.Plugins.Filesystem.writeFile({
                            //     path: 'file:///data/user/0/com.substanzen.app/databases/SubstancesSQLite.db',
                            //     data: resp.data,
                            //     encoding: 'ascii',
                        }).then((result) => {
                            console.log(result)
                        });
                    });
            });
        } catch (err) {
            console.log(`Error: ${err} `);
            throw new Error(`Error: ${err}`)
        }
```
How can I fix this?

**Comment by diachedelic** [comment]
I forgot, you also will need to include the Filesystem plugin for fallback mode to work correctly:

```html
<script src="path/to/node_modules/@capacitor/filesystem/dist/plugin.js"></script>
```

You are right, blob_writer.umd.js is the correct script.

There is no `Plugins.write_blob`. You must use the function provided by blob_writer.umd.js directly: `window.capacitor_blob_writer`.

**Comment by Sempervivum** [comment]
Thanks for the quick reply. This is a huge step forward: The script is running without errors now.
However after the data is written to the database directory it's size is 0 although the response of the HTTP request seems to be correct:
![response-from-http-get](https://github.com/diachedelic/capacitor-blob-writer/assets/6693087/335e7396-464b-49ab-8c82-ef455f640293)
The content-length in the header matches the size of my file exactly.
The script:
```
        try {
            Capacitor.Plugins.Filesystem.requestPermissions().then((status) => {
                console.log(status);
                Capacitor.Plugins.CapacitorHttp.get({
                    url: 'https://webentwicklung.ulrichbangert.de/_benni/substanzen-electron/Substances.db',
                    responseType: 'blob'
                }).then(function ({ data }) {
                    console.log(data.length);
                    window.capacitor_blob_writer({
                        path: 'file:///data/user/0/com.substanzen.app/databases/SubstancesSQLite.db',
                        data: data.data,
                        fast_mode: true
                    });
                });
            });
        } catch (err) {
            console.log(`Error: ${err} `);
            throw new Error(`Error: ${err}`)
        }
```

**Comment by diachedelic** [comment]
There are some problems with your code.

1. Your try...catch block does nothing. Read this article before continuing: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises.
2. `capacitor_blob_writer` has no "data" option, only a "blob" option.
3. The whole point of this plugin is to avoid encoding and decoding large Base64 strings, but that is exactly what the CapacitorHttp plugin does. Either use `window.fetch` with the BlobWriter plugin, or CapacitorHttp with the Filesystem plugin. (A 2MB file does not warrant the inclusion of the BlobWriter plugin - the Filesystem plugin can handle that just fine.)

**Comment by Sempervivum** [comment]
I followed your recommendations:

- removed try-catch
- used window.fetch

I had to create a PHP file to make the file accessible for cross domain access and now the file is downloading fine, size of the blob is correct.
```
        Capacitor.Plugins.Filesystem.requestPermissions().then((status) => {
            console.log(status);
            fetch('https://webentwicklung.ulrichbangert.de/_benni/db-cors.php')
                .then(response => response.blob())
                .then(blob => {
                    console.log(blob);
                    window.capacitor_blob_writer({
                        path: 'file:///data/user/0/com.substanzen.app/databases/SubstancesSQLite.db',
                        data: blob,
                        fast_mode: true
                    });
                });
        });
```
Unfortunately I keep getting a file of size 0. The time of the file is updated, thus it is written by the app.
![blobwriter-issue-2](https://github.com/diachedelic/capacitor-blob-writer/assets/6693087/fa619e9f-4888-47f8-8ab9-11edf61631fc)

**Comment by diachedelic** [comment]
I have published a new version, v1.1.2, with stricter options checking for `capacitor_blob_writer`. See point (2) above.

**Comment by Sempervivum** [comment]
OMG, silly me, I didn't read point(2) correctly. Success now, the file is created and it's size seems to be correct. Unfortunately Android Studio doesn't display the exact size. The file is a database file of SQLite and I'm curious if it will be read by the sqlite plugin correctly. When storing it by the filesystem plugin I encountered issues that the file was malformed.
Many thanks for the great support!

**Comment by diachedelic** [comment]
You can check the size of a file on disk with Filesystem.stat: https://capacitorjs.com/docs/apis/filesystem#stat.
