### ISSUE TITLE
Unable to install on ios because GCDWebServer dependency fails to download

### ISSUE THREAD

**Issue by nianeyna** [diachedelic/capacitor-blob-writer#71]
Steps to reproduce: Create a new capacitor project and add ios target. Install capacitor-blob-writer using npm, then run `npx cap sync` (on a Mac computer with development environment set up per capacitor docs)

Expected result: Dependencies are installed and capacitor-blob-writer can be used

Actual result: Installation fails because GCDWebServer cannot be downloaded

Example error message:
`CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/7/2/d/GCDWebServer/{version}/GCDWebServer.podspec.json Response: Couldn't connect to server`

Android remains serenely unaffected by this problem, for what it's worth.

**Comment by diachedelic** [comment]
Looks like the `{version}` in that URL is not being substituted by CocoaPods. This URL works fine: https://cdn.jsdelivr.net/cocoa/Specs/7/2/d/GCDWebServer/3.5.4/GCDWebServer.podspec.json.

What version of CocoaPods are you using? I ran `pod --version` and got 1.12.1.

**Comment by diachedelic** [comment]
Works on my machine.

```$ npx cap sync
[warn] The bundledWebRuntime configuration option has been deprecated. Can be
       safely deleted.
✔ Copying web assets from dist to ios/App/App/public in 3.27ms
✔ Creating capacitor.config.json in ios/App/App in 659.25μs
✔ copy ios in 8.67ms
✔ Updating iOS plugins in 587.79μs
[info] Found 3 Capacitor plugins for ios:
       @capacitor/camera@5.0.7
       @capacitor/splash-screen@5.0.6
       capacitor-blob-writer@1.1.14
✔ Updating iOS native dependencies with pod install in 21.68s
✔ update ios in 21.71s
✔ copy web in 889.50μs
✔ update web in 172.75μs
[info] Sync finished in 22.15s
$
```

Please let me know if you find out what's wrong.

**Comment by nianeyna** [comment]
> Looks like the `{version}` in that URL is not being substituted by CocoaPods. This URL works fine: https://cdn.jsdelivr.net/cocoa/Specs/7/2/d/GCDWebServer/3.5.4/GCDWebServer.podspec.json.
> 
> What version of CocoaPods are you using? I ran `pod --version` and got 1.12.1.

Oh weird, clicking on that link just in my browser gave me a "problem loading page" error. Given that, it sounds like this is probably a network issue on my end. I'll troubleshoot from there - sorry for the bother!
