### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by wills01** [diachedelic/capacitor-blob-writer#76]
unhandledRejection .....\node_modules\capacitor-blob-writer\blob_writer.js:3
import {Capacitor, registerPlugin} from "@capacitor/core";
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by diachedelic** [comment]
Your compiler is misinterpreting interpret blob_writer.js as a CommonJS module when it is actually an ES module. It should be using blob_writer.umd.js, which is compatible with CommonJS. See package.json.

**Comment by diachedelic** [comment]
Please try v1.1.18.

**Comment by wills01** [comment]
tried v1.1.19
compiles
now getting files on android

But weird thing is happening, the files are almost twice the original size, and cannot open in native apps, i.e. pdf or image says invalid format.  I write to the datadirectory.documents

**Comment by diachedelic** [comment]
Strange. Try running the [demo](https://github.com/diachedelic/capacitor-blob-writer/tree/master/demo) to see if the tests pass on your device.

**Comment by wills01** [comment]
FYI found the issue with doubling size and invalid format, it's a capacitor issue on Android/IOS.
when using capacitor it translates the fetch to use native, however in their wisdom the response is typed as Blob, but actually returns a Base64 encoded Blob, which is no use to anyone. 

[https://github.com/ionic-team/capacitor/issues/6241](https://github.com/ionic-team/capacitor/issues/6241)

Still in current version

**Comment by diachedelic** [comment]
Thanks.
